{{- if and (not .Values.existingSecret) .Values.ovh.applicationKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ovh-baremetal-ccm.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ovh-baremetal-ccm.labels" . | nindent 4 }}
type: Opaque
stringData:
  endpoint: {{ .Values.ovh.endpoint | quote }}
  application_key: {{ .Values.ovh.applicationKey | quote }}
  application_secret: {{ .Values.ovh.applicationSecret | quote }}
  consumer_key: {{ .Values.ovh.consumerKey | quote }}
{{- end }}
